### ISSUE TITLE
move bgImages into src/lib/themes.js as a shared export

### ISSUE THREAD

**Issue by pdehaan** [mozilla/Themer#148]
Per @lmorchard's https://github.com/mozilla/Themer/pull/144/files#r173509750 comment:

> Actually, what might be a good idea is to move `bgImages` into `src/lib/themes.js` as a shared export since we use it both in the add-on and the website. But, I wouldn't block this PR to do it.

**Comment by Shruti9520** [comment]
Hi @pdehaan Can I take this issue?

**Comment by Shruti9520** [comment]
@lmorchard @pdehaan I have a doubt. In Firefox, I opened `about:debugging` and then loaded the build/extension/manifest.json file. But after visiting `http://localhost:8080`, I can't see any web-based theme editor. What I got is- 
![addtheme](https://user-images.githubusercontent.com/20228417/37244242-d644a1ca-24ab-11e8-8959-bd04f36d3710.png)

I tried  `http://localhost:8080/?theme` URL too.

 My `about:debugging` page looks like this-
![themeaddon](https://user-images.githubusercontent.com/20228417/37244263-283dd0e6-24ac-11e8-8c8a-309553b98fc0.png)

Am I using the wrong URL?

Thanks!

**Comment by Shruti9520** [comment]
@pdehaan @lmorchard **Issue is solved**! :-)  
Actually, URL is `http://localhost:8081`.  See the screenshot below->

![themersolve](https://user-images.githubusercontent.com/20228417/37244625-c5a8dd8a-24b1-11e8-86aa-d59ca999d69d.png)

I will not delete my previous comment because it will help any new contributor to get started. :-)

Thanks!

**Comment by Shruti9520** [comment]
Hi @pdehaan @lmorchard @johngruen 
When I click on the "ThemesRFun" toolbar button, it opens up a tab with URL `http://localhost:8081`. Please see the uploaded gif below-
![themer-2018-03-11_01 02 12](https://user-images.githubusercontent.com/20228417/37246160-05e33d06-24ca-11e8-87d8-b17a6b3d292a.gif)

Can I open an issue for this?

Thanks!

**Comment by 94151** [comment]
@lmorchard is this issue still active? can I start work on this?

**Comment by lmorchard** [comment]
>  I have a doubt. In Firefox, I opened about:debugging and then loaded the build/extension/manifest.json file. But after visiting http://localhost:8080, I can't see any web-based theme editor.

@Shruti9520 It look like you're using Ubuntu for development and you already have a Tomcat server running on port 8080. That's why you're seeing the "It Works!" page instead. 

I just submitted PR #161 to make it possible to change the port used for this project. But until that's ready to use, you might want to look at disabling your Tomcat server. I'm not very familiar with Tomcat these days, but I think you can stop it with something like `sudo /etc/init.d/tomcat5.5 stop`

**Comment by lmorchard** [comment]
@94151 I think @Shruti9520 has been working on this one, but more help is always welcome

**Comment by lmorchard** [comment]
d3aa16e085b1f8d7b58474b4fccc9b467b527312
