### ISSUE TITLE
Wrong tooltip is displayed when the "Themes Textures" are hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#193]
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.32 custom build from 2018-03-21) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Theme Texture" bubble
3. Hover any theme texture and observe the displayed tooltip.

**[Expected result]:**
- For each texture a related tooltip is displayed.

**[Actual result]:**
- The "Theme Texture" tooltip is displayed.

**[Notes]:**.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37721589-969a3226-2d32-11e8-9555-bd3e3eeb5e00.gif)

**Comment by shr7** [comment]
What should be the tooltip for each texture? 
backgroundId?

**Comment by lmorchard** [comment]
We don't have names for the textures at this point. Better fix is probably just to move the title in ThemeBackgroundPicker from [the <div>](https://github.com/mozilla/Themer/blob/master/src/web/lib/components/ThemeBackgroundPicker/index.js#L77) to the [__swatch](https://github.com/mozilla/Themer/blob/master/src/web/lib/components/ThemeBackgroundPicker/index.js#L79) and [__text](https://github.com/mozilla/Themer/blob/master/src/web/lib/components/ThemeBackgroundPicker/index.js#L86) spans so that the __backgrounds element doesn't get the title.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Themer" add-on (0.0.33 custom built on 29.03.2018) installed, on the latest Firefox release and Nightly. Now the tooltips are no longer displayed. Verified on Windows 10 x64, Arch Linux and Mac 10.12.
