### ISSUE TITLE
Ensure responsive styles work down to 640px width

### ISSUE THREAD

**Issue by lmorchard** [mozilla/Themer#41]
From [acceptance criteria](https://github.com/mozilla/ThemesRFun/blob/master/docs/acceptance.md):

> - [ ] It should be functionally responsive down to 640px.

Another final checklist item for near the end

**Comment by youwenliang** [comment]
For responsive view I was thinking something like this:

width 1200px
<img width="512" alt="image" src="https://user-images.githubusercontent.com/8919308/35953241-9b08190c-0cbe-11e8-90e5-e65583f72504.png">

width over 1200px
<img width="512" alt="image" src="https://user-images.githubusercontent.com/8919308/35953246-a312d934-0cbe-11e8-9348-a08536a4152a.png">

width below 1200px and above 640px
<img width="512" alt="image" src="https://user-images.githubusercontent.com/8919308/35953254-adda70fc-0cbe-11e8-90ef-b16beaaeaa3d.png">

As for width below 640px or on mobile device, it'll be a static screen with text and image saying ThemesRFun is a desktop experiment so best view on desktop. We will provide this screen soon.

**Comment by Shruti9520** [comment]
Can I work on this issue? :-)

**Comment by lmorchard** [comment]
> Can I work on this issue? :-)

Missed this comment yesterday, but sure!

**Comment by Shruti9520** [comment]
Hi, @lmorchard @pdehaan 
How to get `custom theme` and `popular theme`? What I am getting in `localhost:8081` is this-
![thm](https://user-images.githubusercontent.com/20228417/37560668-af7bc19c-2a62-11e8-9939-2c418b8cc8f7.png)

@pdehaan told me before that  “ThemesRFun” was the beta name, and “Themer” is the final name. So, I can clearly get why the screenshot in the above issue is showing `www.themerunFun.com`. But I am little confused why the screenshot given in this issue is different from what I am getting in my localhost.

Thanks!

**Comment by pdehaan** [comment]
@Shruti9520, 

Sorry, I think those may have been an old design spec. We may have to ping @johngruen and @youwenliang to see if they have a link to the latest mobile designs.

**Comment by Shruti9520** [comment]
@pdehaan Thanks! :-)
